// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kfi-redesign/BrightWorkshop.tsx": () => import("../components/mockups/kfi-redesign/BrightWorkshop.tsx"),
  "./components/mockups/kfi-redesign/ConfidentDispatch.tsx": () => import("../components/mockups/kfi-redesign/ConfidentDispatch.tsx"),
  "./components/mockups/kfi-redesign/SoftClinical.tsx": () => import("../components/mockups/kfi-redesign/SoftClinical.tsx"),
  "./components/mockups/kfi-redesign/WarmEditorial.tsx": () => import("../components/mockups/kfi-redesign/WarmEditorial.tsx")
};
